[package]
name = "qr_code_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
nfd2 = "0.3.1"
qrcode = "0.14.1"
rand = "0.8.5"
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"
