import { TextEdit, Button, HorizontalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
  title: "qr_code_genarator";

  in property <image> qrcode;
  in property <string> file-id;
  in property <int> save-count;
  in-out property <bool> is-save-success: false;
  
  callback generate-qrcode(string);
  callback save-qrcode();

  VerticalLayout {
    padding: 50px;
    spacing: 20px;

    popup := PopupWindow {
      Text {
        text: "- 保存成功 -";
        font-size: 12px;
        color: #00b300;
      }
      x: parent.width / 2.5;
      y: 10px;
    }

    timer := Timer {
      interval: 2s;
      running: false;
      triggered() => {
        self.running = false;
        popup.close();
        is-save-success = false;
      }
    }

    Text {
      text: "二维码生成器";
      font-size: 20px;
      font-weight: 500;
      horizontal-alignment: center;
    }

    te := TextEdit {
      placeholder-text: "在此输入二维码内容";
      font-size: 13px;
      height: 80px;
    }

    Button {
      text: "生成二维码";
      enabled: te.text != "";
      clicked => {
        root.generate-qrcode(te.text);
        te.text = "";
      }
    }

    Button {
      text: "图片另存为";
      enabled: qrcode.width > 0;
      clicked => {
        root.save-qrcode();
        if (is-save-success) {
          popup.show();
          timer.running = true;
        }
      }
    }

    HorizontalBox {
      alignment: center;
      width: 232px;
      height: 232px;

      Image {
        source: qrcode;
      }
    }
  }
}